config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('accounts.urls')),
    path('',include('posts.urls')),


]

posts/urls.py
from django.urls import path
from .views import *
from .models import *


app_name='posts'


urlpatterns=[
   path('',searchresult,name='query_list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 {% load static %}
      <link rel="stylesheet" href="{% static 'style.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Dstagram {% block title %}{% endblock %}</title>


</head>


{% endblock %}
<body>


<div class="container">
<div class="row">
    <div class="col-lg-1 brand-name">
         <a class="navbar-brand" href="/"><h3>FOOGLE</h3></a>

    </div>
    <div class="col-lg-11 card-margin">
        <div class="card search-form">
            <div class="card-body p-0">
                <form id="search-form">
                    <div class="row">
                        <div class="col-12">

                            <div class="row no-gutters">

                               <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                    <select class="form-control" id="exampleFormControlSelect1" name="drop">
                                        <option value="1"  >전체 </option>
                                        <option value="79"  >옷 후기</option>
                                        <option value="26" >데일리룩 </option>
                                        <option value="109" >자유게시판 </option>
                                        <option value="64" >질문게시판 </option>
                                    </select>
                                </div>

                                <div class="col-lg-8 col-md-6 col-sm-12 p-0">
                                <form method="GET" action="{%url 'posts:query_list' %}">
                                        {% csrf_token %}
                                    <input type="text" placeholder="Search..." class="form-control" id="search" name="q">
                                </form>
                                </div>
                                <div class="col-lg-1 col-md-3 col-sm-12 p-0">
                                    <button type="submit" class="btn btn-base">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
                                    </button>

                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    {% block content %}





    {% endblock %}

    <footer class="footer">
        <p>&copy; 2020 Hyunsik. Powered By Django 3</p>
    </footer>
</div>


</body>
</html>